name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Angular
        run: |
          npx ng build --configuration production --base-href "/radar-aps/"

      # >>> ESSENCIAL para Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Resolve dist path (radar-aps)
        id: distpath
        shell: bash
        run: |
          set -euo pipefail
          DIST_DIR="dist/radar-aps"
          if [ -d "$DIST_DIR/browser" ]; then
            FINAL="$DIST_DIR/browser"
          elif [ -d "$DIST_DIR" ]; then
            FINAL="$DIST_DIR"
          else
            echo "Nenhuma pasta dist encontrada. Conteúdo de dist/:" >&2
            ls -R dist || true
            exit 1
          fi
          echo "path=$FINAL" >> "$GITHUB_OUTPUT"
          echo "Detected dist path: $FINAL"

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.distpath.outputs.path }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
