name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Build Angular (ajuste o base-href conforme o nome do repositório)
      - name: Build Angular
        run: npx ng build --configuration production --base-href "/radar-aps/"

      # Detecta a pasta correta lendo o angular.json
      - name: Detect dist path
        id: dist
        shell: bash
        run: |
          OUT=$(node -e "const a=require('./angular.json');\
            const app=Object.keys(a.projects).find(p=>a.projects[p].projectType==='application')||Object.keys(a.projects)[0];\
            const opts=(a.projects[app].architect?.build?.options||(a.projects[app].targets?.build?.options)||{});\
            const out=opts.outputPath || ('dist/'+app);\
            process.stdout.write(out)")
          if [ -d \"$OUT/browser\" ]; then
            PATH_TO_USE=\"$OUT/browser\"
          else
            PATH_TO_USE=\"$OUT\"
          fi
          echo \"path=$PATH_TO_USE\" >> $GITHUB_OUTPUT
          echo \"Usando dist: $PATH_TO_USE\"
          ls -la \"$PATH_TO_USE\"

      # SPA fallback para funcionar refresh em rotas
      - name: SPA 404 fallback
        shell: bash
        run: |
          if [ -f "${{ steps.dist.outputs.path }}/index.html" ]; then
            cp "${{ steps.dist.outputs.path }}/index.html" "${{ steps.dist.outputs.path }}/404.html"
          else
            echo "index.html não encontrado em ${{ steps.dist.outputs.path }}"
            exit 1
          fi

      - uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ steps.dist.outputs.path }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
