name: Deploy Angular to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Build Angular (ajuste o base-href conforme o nome do repositório)
      - name: Build Angular
        run: npx ng build --configuration production --base-href "/radar-aps/"

      # Detecta a pasta correta do build
      - name: Set dist path
        id: dist
        run: |
          if [ -d "dist/radar-aps/browser" ]; then
            echo "path=dist/radar-aps/browser" >> $GITHUB_OUTPUT
            echo "Usando dist: dist/radar-aps/browser"
            ls -la dist/radar-aps/browser
          elif [ -d "dist/radar-aps" ]; then
            echo "path=dist/radar-aps" >> $GITHUB_OUTPUT
            echo "Usando dist: dist/radar-aps"
            ls -la dist/radar-aps
          else
            echo "Erro: Pasta dist não encontrada"
            ls -la dist/
            exit 1
          fi

      # SPA fallback para funcionar refresh em rotas
      - name: SPA 404 fallback
        shell: bash
        run: |
          if [ -f "${{ steps.dist.outputs.path }}/index.html" ]; then
            cp "${{ steps.dist.outputs.path }}/index.html" "${{ steps.dist.outputs.path }}/404.html"
          else
            echo "index.html não encontrado em ${{ steps.dist.outputs.path }}"
            exit 1
          fi

      - uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ steps.dist.outputs.path }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
